// ── BOOKS DATA ── edit this file to add/remove books ──────────────────────
const BOOKS = [
  // AI & TECH
  {title:"AGI",img:"Ai/agi.jpg",url:"Ai/agi.html",cat:"ai",tag:"AI & Tech"},
  {title:"AI Life",img:"Ai/ai life.jpg",url:"Ai/ai life.html",cat:"ai",tag:"AI & Tech"},
  {title:"AI Big Data",img:"Ai/aibigdata.jpg",url:"Ai/aibigdata.html",cat:"ai",tag:"AI & Tech"},
  {title:"AI Principles",img:"Ai/aip.jpg",url:"Ai/aip.html",cat:"ai",tag:"AI & Tech"},
  {title:"ARPANET Technical",img:"Ai/ARPANET Technical.jpg",url:"Ai/ARPANET Technical.html",cat:"ai",tag:"AI & Tech"},
  {title:"Black Book of Communism",img:"Ai/Black Book of Communism.jpg",url:"Ai/Black Book of Communism.html",cat:"ai",tag:"AI & Tech"},
  {title:"Book of Soyga",img:"Ai/Book of Soyga.jpg",url:"Ai/Book of Soyga.html",cat:"ai",tag:"AI & Tech"},
  {title:"Chrysopoeia of Cleopatra",img:"Ai/Chrysopoeia of Cleopatra.jpg",url:"Ai/Chrysopoeia of Cleopatra.html",cat:"ai",tag:"AI & Tech"},
  {title:"Computing in the Age of AI",img:"Ai/Computing in the age of ai.jpg",url:"Ai/Computing in the age of ai.html",cat:"ai",tag:"AI & Tech"},
  {title:"DevOps",img:"Ai/devops.jpeg",url:"Ai/debops.html",cat:"ai",tag:"AI & Tech"},
  {title:"Genesis",img:"Ai/Genesis.jpg",url:"Ai/Genesis.html",cat:"ai",tag:"AI & Tech"},
  {title:"Gospel of Judas",img:"Ai/Gospel of Judas.jpg",url:"Ai/Gospel of Judas.html",cat:"ai",tag:"AI & Tech"},
  {title:"History of AI",img:"Ai/History of ai.jpg",url:"Ai/History of ai.html",cat:"ai",tag:"AI & Tech"},
  {title:"Master Algorithm",img:"Ai/Master_Algorithm.jpg",url:"Ai/Master_Algorithm.html",cat:"ai",tag:"AI & Tech"},
  {title:"Mitrokhin Archive",img:"Ai/Mitrokhin Archive.jpg",url:"Ai/Mitrokhin Archive.html",cat:"ai",tag:"AI & Tech"},
  {title:"Nexus",img:"Ai/Nexus.jpg",url:"Ai/Nexus.html",cat:"ai",tag:"AI & Tech"},
  {title:"Pentagon Papers",img:"Ai/Pentagon Papers.jpg",url:"Ai/Pentagon Papers.html",cat:"ai",tag:"AI & Tech"},
  {title:"Raziel Angel",img:"Ai/Raziel_Angel.jpg",url:"Ai/Raziel_Angel.html",cat:"ai",tag:"AI & Tech"},
  {title:"Revenge",img:"Ai/Revenge.jpg",url:"Ai/Revenge.html",cat:"ai",tag:"AI & Tech"},
  {title:"Sapiens",img:"Ai/Sapiens.jpg",url:"Ai/Sapiens.html",cat:"ai",tag:"AI & Tech"},
  {title:"Second Machine Age",img:"Ai/Second_Machine_Age.jpg",url:"Ai/Second_Machine_Age.html",cat:"ai",tag:"AI & Tech"},
  {title:"Sefer Raziel",img:"Ai/Sefer Raziel.jpg",url:"Ai/Sefer Raziel.html",cat:"ai",tag:"AI & Tech"},
  {title:"Stargate Project",img:"Ai/Stargate Project.jpg",url:"Ai/Stargate Project.html",cat:"ai",tag:"AI & Tech"},
  {title:"The Existential Pleasures of Engineering",img:"Ai/The Existential Pleasures of Engineering.jpg",url:"Ai/The Existential Pleasures of Engineering.html",cat:"ai",tag:"AI & Tech"},
  {title:"The Humor Code",img:"Ai/The Humor Code.jpg",url:"Ai/The Humor Code.html",cat:"ai",tag:"AI & Tech"},
  {title:"The Industrial Revolution",img:"Ai/The Industrial Revolution.jpg",url:"Ai/The Industrial Revolution.html",cat:"ai",tag:"AI & Tech"},
  {title:"The Voynich Manuscript",img:"Ai/The Voynich Manuscript.jpg",url:"Ai/The Voynich Manuscript.html",cat:"ai",tag:"AI & Tech"},
  {title:"ULTRA Intelligence",img:"Ai/ULTRA Intelligence & Military Codebooks.jpg",url:"Ai/ULTRA Intelligence & Military Codebooks.html",cat:"ai",tag:"AI & Tech"},
  // BUSINESS
  {title:"Zero to One",img:"Business/Zero to One.jpg",url:"Business/0to1.html",cat:"business",tag:"Business"},
  {title:"10x",img:"Business/10x.jpg",url:"Business/10x.html",cat:"business",tag:"Business"},
  {title:"5 Types of Wealth",img:"Business/5typewealth.jpg",url:"Business/5typewealth.html",cat:"business",tag:"Business"},
  {title:"80/20 Principle",img:"Business/8020.png",url:"Business/8020.html",cat:"business",tag:"Business"},
  {title:"Big Money",img:"Business/bigmoney.jpg",url:"Business/bigmoney.html",cat:"business",tag:"Business"},
  {title:"Bitcoin",img:"Business/Bitcoin.jpg",url:"Business/Bitcoin.html",cat:"business",tag:"Business"},
  {title:"Clockwork",img:"Business/Clockwork.jpg",url:"Business/Clockwork.html",cat:"business",tag:"Business"},
  {title:"Deep Value",img:"Business/deep value.jpg",url:"Business/deep value.html",cat:"business",tag:"Business"},
  {title:"Deep Work",img:"Business/Deep Work.jpg",url:"Business/Deep Work.html",cat:"business",tag:"Business"},
  {title:"Design Work",img:"Business/designwork.jpg",url:"Business/designwork.html",cat:"business",tag:"Business"},
  {title:"Exponential Organizations",img:"Business/Exponential Organizations.jpg",url:"Business/Exponential Organizations.html",cat:"business",tag:"Business"},
  {title:"Financial Shenanigans",img:"Business/Financial Shenanigans.jpg",url:"Business/Financial Shenanigans.html",cat:"business",tag:"Business"},
  {title:"Follow the Fed",img:"Business/followfed.jpeg",url:"Business/followfed.html",cat:"business",tag:"Business"},
  {title:"Good to Great",img:"Business/good.png",url:"Business/good.html",cat:"business",tag:"Business"},
  {title:"Hidden Potential",img:"Business/Hidden Potential.jpg",url:"Business/Hidden Potential.html",cat:"business",tag:"Business"},
  {title:"Hard Work",img:"Business/hwork.jpg",url:"Business/hwork.html",cat:"business",tag:"Business"},
  {title:"Killing Marketing",img:"Business/Killing Marketing.jpg",url:"Business/Killing Marketing.html",cat:"business",tag:"Business"},
  {title:"Leader Ask",img:"Business/leader_ask.jpg",url:"Business/leader_ask.html",cat:"business",tag:"Business"},
  {title:"Leadership & Self-Deception",img:"Business/Leadership and Self-Deception.jpg",url:"Business/Leadership and Self-Deception.html",cat:"business",tag:"Business"},
  {title:"Lean Entrepreneur",img:"Business/lean enterpreneur.jpg",url:"Business/lean enterpreneur.html",cat:"business",tag:"Business"},
  {title:"The Lean Startup",img:"Business/The Lean Startup.jpg",url:"Business/LeanStartup.html",cat:"business",tag:"Business"},
  {title:"Money for Nothing",img:"Business/Money for Nothing.jpg",url:"Business/Money for Nothing.html",cat:"business",tag:"Business"},
  {title:"Multipliers",img:"Business/Multipliers.jpeg",url:"Business/Multipliers.html",cat:"business",tag:"Business"},
  {title:"NEA",img:"Business/nea.jpeg",url:"Business/nea.html",cat:"business",tag:"Business"},
  {title:"Profit First",img:"Business/profitfirst.jpg",url:"Business/profitfirst.html",cat:"business",tag:"Business"},
  {title:"Promote Yourself",img:"Business/PromoteU.jpg",url:"Business/PromoteU.html",cat:"business",tag:"Business"},
  {title:"Reinventing Organizations",img:"Business/Reinventing_org.jpg",url:"Business/Reinventing_org.html",cat:"business",tag:"Business"},
  {title:"Rich Dad Poor Dad",img:"Business/Rich Dad Poor Dad.jpg",url:"Business/Rich Dad Poor Dad.html",cat:"business",tag:"Business"},
  {title:"Running Lean",img:"Business/running lean.jpg",url:"Business/running lean.html",cat:"business",tag:"Business"},
  {title:"Same as Ever",img:"Business/same as ever.jpeg",url:"Business/same as ever.html",cat:"business",tag:"Business"},
  {title:"Scaling Up Excellence",img:"Business/Scaling Up Excellence.jpg",url:"Business/Scaling Up Excellence.html",cat:"business",tag:"Business"},
  {title:"Seeing What's Next",img:"Business/seeing what's next.jpg",url:"Business/seeing what's next.html",cat:"business",tag:"Business"},
  {title:"Simple Path to Wealth",img:"Business/simple path to wealth.jpg",url:"Business/simple path to wealth.html",cat:"business",tag:"Business"},
  {title:"Strategy Safari",img:"Business/Strategy Safari.jpg",url:"Business/Strategy Safari.html",cat:"business",tag:"Business"},
  {title:"Success System",img:"Business/successsystem.jpg",url:"Business/successsystem.html",cat:"business",tag:"Business"},
  {title:"The Content Trap",img:"Business/The Content Trap.jpg",url:"Business/The Content Trap.html",cat:"business",tag:"Business"},
  {title:"The End of Advertising",img:"Business/The End of Advertising.jpg",url:"Business/The End of Advertising.html",cat:"business",tag:"Business"},
  {title:"Psychology of Money",img:"Business/The Psychology of Money.jpg",url:"Business/The Psychology of Money.html",cat:"business",tag:"Business"},
  {title:"Strategy Paradox",img:"Business/The Strategy Paradox.jpg",url:"Business/The Strategy Paradox.html",cat:"business",tag:"Business"},
  {title:"Tribal Leadership",img:"Business/Tribal Leadership.jpg",url:"Business/Tribal Leadership.html",cat:"business",tag:"Business"},
  {title:"Win",img:"Business/win.png",url:"Business/win.html",cat:"business",tag:"Business"},
  // BRAIN
  {title:"2nd Brain",img:"Health/Brain/2ndbrain.webp",url:"Health/Brain/2ndbrain.html",cat:"brain",tag:"Brain"},
  {title:"7 Habits",img:"Health/Brain/7Habit.jpg",url:"Health/Brain/7Habit.html",cat:"brain",tag:"Brain"},
  {title:"Art & Science",img:"Health/Brain/aascience.jpg",url:"Health/Brain/aascience.html",cat:"brain",tag:"Brain"},
  {title:"ALM",img:"Health/Brain/alm.jpeg",url:"Health/Brain/alm.html",cat:"brain",tag:"Brain"},
  {title:"A Memory",img:"Health/Brain/amemory.jpg",url:"Health/Brain/amemory.html",cat:"brain",tag:"Brain"},
  {title:"Atomic Habits",img:"Health/Brain/Atomic Habits.jpg",url:"Health/Brain/Atomic Habits.html",cat:"brain",tag:"Brain"},
  {title:"Behave",img:"Health/Brain/behave.jpeg",url:"Health/Brain/behave.html",cat:"brain",tag:"Brain"},
  {title:"Brain Energy",img:"Health/Brain/brain energy.jpeg",url:"Health/Brain/brain energy.html",cat:"brain",tag:"Brain"},
  {title:"Brain Music",img:"Health/Brain/brain music.jpeg",url:"Health/Brain/brain music .html",cat:"brain",tag:"Brain"},
  {title:"Brain Change",img:"Health/Brain/brain_change.jpg",url:"Health/Brain/brain_change.html",cat:"brain",tag:"Brain"},
  {title:"Brain Secret",img:"Health/Brain/brain_secret.jpg",url:"Health/Brain/brain_secret.html",cat:"brain",tag:"Brain"},
  {title:"Buildings Learn",img:"Health/Brain/Buildings_Learn.jpg",url:"Health/Brain/Buildings_Learn.html",cat:"brain",tag:"Brain"},
  {title:"Culture Code",img:"Health/Brain/Culture Code.jpg",url:"Health/Brain/Culture Code.html",cat:"brain",tag:"Brain"},
  {title:"Determined",img:"Health/Brain/determined.png",url:"Health/Brain/determined.html",cat:"brain",tag:"Brain"},
  {title:"Expand Mind",img:"Health/Brain/expendmind.jpg",url:"Health/Brain/expendmind.html",cat:"brain",tag:"Brain"},
  {title:"Thinking Fast & Slow",img:"Health/Brain/fastandslow.jpg",url:"Health/Brain/fastandslow.html",cat:"brain",tag:"Brain"},
  {title:"Good Energy",img:"Health/Brain/Good Energy.jpeg",url:"Health/Brain/Good Energy.html",cat:"brain",tag:"Brain"},
  {title:"Invisible Influence",img:"Health/Brain/invisible influence.jpg",url:"Health/Brain/invisible influence.html",cat:"brain",tag:"Brain"},
  {title:"Most Important Thing",img:"Health/Brain/most important thing.jpg",url:"Health/Brain/most important thing.html",cat:"brain",tag:"Brain"},
  {title:"Organized Mind",img:"Health/Brain/organized mind.jpeg",url:"Health/Brain/organized mind.html",cat:"brain",tag:"Brain"},
  {title:"PARA",img:"Health/Brain/para.jpg",url:"Health/Brain/para.html",cat:"brain",tag:"Brain"},
  {title:"Peak Performance",img:"Health/Brain/peak_performance.jpeg",url:"Health/Brain/peak_performance.html",cat:"brain",tag:"Brain"},
  {title:"Photo Memory",img:"Health/Brain/PhotoMemory.jpg",url:"Health/Brain/PhotoMemory.html",cat:"brain",tag:"Brain"},
  {title:"Power of Habit",img:"Health/Brain/Power_of_habit.jpg",url:"Health/Brain/Power_of_habit.html",cat:"brain",tag:"Brain"},
  {title:"Psychology of Love",img:"Health/Brain/psychology_love.jpg",url:"Health/Brain/psychology_love.html",cat:"brain",tag:"Brain"},
  {title:"Righteous Mind",img:"Health/Brain/Righteous_Mind.jpg",url:"Health/Brain/Righteous_Mind.html",cat:"brain",tag:"Brain"},
  {title:"Slow Pro",img:"Health/Brain/slowpro.jpeg",url:"Health/Brain/Slowpro.html",cat:"brain",tag:"Brain"},
  {title:"The Changing Mind",img:"Health/Brain/The Changing Mind.jpeg",url:"Health/Brain/The Changing Mind.html",cat:"brain",tag:"Brain"},
  {title:"Little Black Book of Innovation",img:"Health/Brain/The Little Black Book of Innovation.jpg",url:"Health/Brain/The Little Black Book of Innovation.html",cat:"brain",tag:"Brain"},
  {title:"Power of Subconscious Mind",img:"Health/Brain/The Power of Your Subconscious Mind.jpeg",url:"Health/Brain/The Power of Your Subconscious Mind.html",cat:"brain",tag:"Brain"},
  {title:"Psychology of Persuasion",img:"Health/Brain/The Psychology of Persuasion.jpg",url:"Health/Brain/The Psychology of Persuasion.html",cat:"brain",tag:"Brain"},
  {title:"Road Less Traveled",img:"Health/Brain/The Road Less Traveled.jpg",url:"Health/Brain/The Road Less Traveled.html",cat:"brain",tag:"Brain"},
  {title:"Tiny Habits",img:"Health/Brain/tinyhabits.jpg",url:"Health/Brain/tinyhabits.html",cat:"brain",tag:"Brain"},
  {title:"Unconscious Mind",img:"Health/Brain/ucmind.jpeg",url:"Health/Brain/ucmind.html",cat:"brain",tag:"Brain"},
  {title:"Weaponized Lies",img:"Health/Brain/Weaponized Lies.jpeg",url:"Health/Brain/Weaponized Lies.html",cat:"brain",tag:"Brain"},
  // HEALTH
  {title:"Best Diet",img:"Health/bestdite.jpg",url:"Health/bestdite.html",cat:"health",tag:"Health"},
  {title:"BNM",img:"Health/bnm.jpg",url:"Health/bnm.html",cat:"health",tag:"Health"},
  {title:"Blue Zone",img:"Health/bzone.jpg",url:"Health/bzone.html",cat:"health",tag:"Health"},
  {title:"Blue Zone 2",img:"Health/bzone2.jpg",url:"Health/bzone2.html",cat:"health",tag:"Health"},
  {title:"Deep Nutrition",img:"Health/Deep Nutrition.jpg",url:"Health/Deep Nutrition.html",cat:"health",tag:"Health"},
  {title:"Design Thinking",img:"Health/designthinking.jpeg",url:"Health/designthinking.html",cat:"health",tag:"Health"},
  {title:"Food",img:"Health/food.jpg",url:"Health/food.html",cat:"health",tag:"Health"},
  {title:"Forever Strong",img:"Health/forever strong.jpeg",url:"Health/forever strong.html",cat:"health",tag:"Health"},
  {title:"GR",img:"Health/gr.jpg",url:"Health/gr.html",cat:"health",tag:"Health"},
  {title:"Healthy Cook",img:"Health/hcook.jpg",url:"Health/hcook.html",cat:"health",tag:"Health"},
  {title:"Healthy Edible",img:"Health/hedible.jpg",url:"Health/hedible.html",cat:"health",tag:"Health"},
  {title:"Health Empire",img:"Health/hempire.jpg",url:"Health/hempire.html",cat:"health",tag:"Health"},
  {title:"How Not to Die",img:"Health/How Not to Die.jpg",url:"Health/How Not to Die.html",cat:"health",tag:"Health"},
  {title:"Outlive",img:"Health/Outlive.jpg",url:"Health/Outlive.html",cat:"health",tag:"Health"},
  {title:"Salt",img:"Health/salt.jpg",url:"Health/salt.html",cat:"health",tag:"Health"},
  {title:"Successful Aging",img:"Health/successful aging.jpeg",url:"Health/successful aging.html",cat:"health",tag:"Health"},
  {title:"Supergut",img:"Health/supergut.png",url:"Health/supergut.html",cat:"health",tag:"Health"},
  {title:"Sweet Power",img:"Health/sweetpower.jpg",url:"Health/sweetpower.html",cat:"health",tag:"Health"},
  {title:"Walk",img:"Health/walk.jpeg",url:"Health/walk.html",cat:"health",tag:"Health"},
  {title:"Why We Sleep",img:"Health/Why We Sleep.jpg",url:"Health/Why We Sleep.html",cat:"health",tag:"Health"},
  // LIFE
  {title:"12 Rules for Life",img:"Life/12rule.jpg",url:"Life/12rule.html",cat:"life",tag:"Life"},
  {title:"The One Thing",img:"Life/1thing.png",url:"Life/1thing.html",cat:"life",tag:"Life"},
  {title:"AI Mind",img:"Life/aimind.jpg",url:"Life/aimind.html",cat:"life",tag:"Life"},
  {title:"All Life",img:"Life/all-life.jpg",url:"Life/all-life.html",cat:"life",tag:"Life"},
  {title:"Anti-Aging",img:"Life/anti-aging.webp",url:"Life/anti-aging.html",cat:"life",tag:"Life"},
  {title:"Atomic Habits",img:"Health/Brain/Atomic Habits.jpg",url:"Life/Atomic Habits.html",cat:"life",tag:"Life"},
  {title:"Be Useful",img:"Life/be useful.jpg",url:"Life/be useful.html",cat:"life",tag:"Life"},
  {title:"Be Happy",img:"Life/bhappy.jpg",url:"Life/bhappy.html",cat:"life",tag:"Life"},
  {title:"Biology of Belief",img:"Life/biobelief.jpg",url:"Life/biobelief.html",cat:"life",tag:"Life"},
  {title:"Blink",img:"Life/blink2.jpg",url:"Life/blink2.html",cat:"life",tag:"Life"},
  {title:"Conversational Intelligence",img:"Life/Conversational-Intelligence.jpeg",url:"Life/Conversational-Intelligence.html",cat:"life",tag:"Life"},
  {title:"Creative Thinking",img:"Life/ct.jpg",url:"Life/create thinking.html",cat:"life",tag:"Life"},
  {title:"Don't Die",img:"Life/dontdie.jpg",url:"Life/Dontdie.html",cat:"life",tag:"Life"},
  {title:"Flow",img:"Life/flow.jpg",url:"Life/flow.html",cat:"life",tag:"Life"},
  {title:"Gentle",img:"Life/gentle.jpg",url:"Life/gentle.html",cat:"life",tag:"Life"},
  {title:"How to Learn",img:"Life/howtolearn.png",url:"Life/howtolearn.html",cat:"life",tag:"Life"},
  {title:"Learn Like a Student",img:"Life/learnstudent.jpeg",url:"Life/learnstudent.html",cat:"life",tag:"Life"},
  {title:"Life 3 Dimensions",img:"Life/life3dimension.jpg",url:"Life/life3dimension.html",cat:"life",tag:"Life"},
  {title:"Life Learning",img:"Life/lifelearning.jpeg",url:"Life/lifelearning.html",cat:"life",tag:"Life"},
  {title:"Life Secret",img:"Life/lifesecret.jpg",url:"Life/Lifesecret.html",cat:"life",tag:"Life"},
  {title:"Lifespan",img:"Life/lifespan.jpg",url:"Life/lifespan.html",cat:"life",tag:"Life"},
  {title:"Mastery",img:"Life/mastery.webp",url:"Life/mastery.html",cat:"life",tag:"Life"},
  {title:"Mindset",img:"Life/mindset2.jpg",url:"Life/mindset2.html",cat:"life",tag:"Life"},
  {title:"Money Making",img:"Life/money-making.jpg",url:"Life/money-making.html",cat:"life",tag:"Life"},
  {title:"Mountain",img:"Life/mountain.jpg",url:"Life/mountain.html",cat:"life",tag:"Life"},
  {title:"Note Life",img:"Life/note-life.jpg",url:"Life/note-life.html",cat:"life",tag:"Life"},
  {title:"Now",img:"Life/now.jpg",url:"Life/now.html",cat:"life",tag:"Life"},
  {title:"Sensory Learning",img:"Life/SensLearn.jpeg",url:"Life/SensLearn.html",cat:"life",tag:"Life"},
  {title:"Steve Jobs",img:"Life/steve-jobs.jpg",url:"Life/steve-jobs.html",cat:"life",tag:"Life"},
  {title:"Success Mindset",img:"Life/mindset2.jpg",url:"Life/success_Mindset.html",cat:"life",tag:"Life"},
  {title:"Supercommunicators",img:"Life/Supercommunicators.jpg",url:"Life/Supercommunicators.html",cat:"life",tag:"Life"},
  {title:"The Age of Choice",img:"Life/The Age of Choice.jpg",url:"Life/The Age of Choice.html",cat:"life",tag:"Life"},
  {title:"Tiny Experiments",img:"Life/Tiny Experiments.jpg",url:"Life/Tiny Experiments.html",cat:"life",tag:"Life"},
  // POWER TOOLS
  {title:"Power Thinking Hub",img:"",url:"Life/Power Thinking/index.html",cat:"power",tag:"Power Tools"},
  {title:"Mental Models Library",img:"",url:"Life/Power Thinking/Mental Models Library.html",cat:"power",tag:"Power Tools"},
  {title:"Decision Framework",img:"",url:"Life/Power Thinking/Decision Making Framework.html",cat:"power",tag:"Power Tools"},
  {title:"Systems Thinking",img:"",url:"Life/Power Thinking/Systems Thinking Analyzer.html",cat:"power",tag:"Power Tools"},
  {title:"Cognitive Bias Detector",img:"",url:"Life/Power Thinking/Cognitive Bias Detector.html",cat:"power",tag:"Power Tools"},
  {title:"Creative Problem Solver",img:"",url:"Life/Power Thinking/Creative Problem Solver.html",cat:"power",tag:"Power Tools"},
  {title:"Munger Mental Models",img:"",url:"Life/Power Thinking/charlie_munger_mental.html",cat:"power",tag:"Power Tools"},
  {title:"Argument Analyzer",img:"",url:"Life/Power Thinking/Argument Structure Analyzer.html",cat:"power",tag:"Power Tools"},
  {title:"Super Think",img:"",url:"Life/Power Thinking/Super Think.html",cat:"power",tag:"Power Tools"},
  {title:"Thinking Coach",img:"",url:"Life/Power Thinking/Thinking Coach.html",cat:"power",tag:"Power Tools"},
  {title:"Autosuggestion Index",img:"",url:"Life/Autosuggetion/index.html",cat:"power",tag:"Power Tools"},
  {title:"Life OS",img:"",url:"Life/Autosuggetion/lifeos.html",cat:"power",tag:"Power Tools"},
  {title:"Psychological Lifehacks",img:"",url:"Life/Autosuggetion/Psychological Lifehacks.html",cat:"power",tag:"Power Tools"},
  {title:"Solve Any Problem",img:"",url:"Life/Autosuggetion/Solve Any Problem.html",cat:"power",tag:"Power Tools"},
  {title:"Ultimate Life Toolkit",img:"",url:"Life/Autosuggetion/ultimate-life-toolkit.html",cat:"power",tag:"Power Tools"},
  {title:"20+ Paradoxes",img:"",url:"Life/Autosuggetion/20+ Paradoxes.html",cat:"power",tag:"Power Tools"},
  {title:"How To Think",img:"",url:"Life/Autosuggetion/How To Think.html",cat:"power",tag:"Power Tools"},
  {title:"Thinking Traps",img:"",url:"Life/Autosuggetion/Thinking Traps.html",cat:"power",tag:"Power Tools"},
];
